#####################################################################
### dtm can be run without any config.
### all config in this file is optional. the default value is as specified in each line
### all configs can be specified from env. for example:
### MicroService.EndPoint => MICRO_SERVICE_END_POINT
#####################################################################

 Store: # specify which engine to store trans status
   Driver: 'mysql'
   Host: 'mysqld'
   User: 'root'
   Password: 'youShouldChangeThis'
   Port: 3306
   Db: 'dtm'

#   Driver: 'boltdb' # default store engine

#   Driver: 'redis'
#   Host: 'localhost'
#   User: ''
#   Password: ''
#   Port: 6379

#   Driver: 'postgres'
#   Host: 'localhost'
#   User: 'postgres'
#   Password: 'mysecretpassword'
#   Port: '5432'

### following config is for only Driver postgres/mysql
#   MaxOpenConns: 500
#   MaxIdleConns: 500
#   ConnMaxLifeTime: 5 # default value is 5 (minutes)

### flollowing config is only for some Driver
#   DataExpire: 604800 # Trans data will expire in 7 days. only for redis/boltdb.
#   FinishedDataExpire: 86400 # finished Trans data will expire in 1 days. only for redis.
#   RedisPrefix: '{a}' # default value is '{a}'. Redis storage prefix. store data to only one slot in cluster

 MicroService: # grpc based microservice config
   Driver: 'dtm-driver-kratos' # name of the driver to handle register/discover
   Target: 'etcd://host.docker.internal:3379/dtmservice' # register dtm server to this url
#   EndPoint: 'grpc://dtm:36790'
   EndPoint: 'grpc://host.docker.internal:36790'

# HttpMicroService: # http based microservice config
#   Driver: 'dtm-driver-http' # name of the driver to handle register/discover
#   RegistryType: 'nacos'
#   RegistryAddress: '127.0.0.1:8848,127.0.0.1:8848'
#   RegistryOptions: '{"namespaceId":"a6843d66-cf5b-43ab-b7e7-461200dfe76c","UserName":"nacos","Password":"nacos","NotLoadCacheAtStart":true}'
#   Target: '{"ServiceName":"dtmService","Enable":true,"Healthy":true,"Weight":10}' # target and options
#   EndPoint: '127.0.0.1:36789'

### the unit of following configurations is second
# TransCronInterval: 3 # the interval to poll unfinished global transaction for every dtm process
# TimeoutToFail: 35 # timeout for XA, TCC to fail. saga's timeout default to infinite, which can be overwritten in saga options
# RetryInterval: 10 # the subtrans branch will be retried after this interval
# RequestTimeout: 3 # the timeout of HTTP/gRPC request in dtm

 LogLevel: 'info'              # default: info. can be debug|info|warn|error
# Log:
#    Outputs: 'stderr'           # default: stderr, split by ",", you can append files to Outputs if need. example:'stderr,/tmp/test.log'
#    RotationEnable: 0           # default: 0
#    RotationConfigJSON: '{}'    # example: '{"maxsize": 100, "maxage": 0, "maxbackups": 0, "localtime": false, "compress": false}'
#
# HttpPort: 36789
# GrpcPort: 36790
# JsonRpcPort: 36791

### advanced options
# UpdateBranchAsyncGoroutineNum: 1 # num of async goroutine to update branch status
 AdminBasePath: "/dtm-ui"