/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1TicketingMedia } from './v1-ticketing-media';

/**
 * 
 * @export
 * @interface V1CreateActivityRequest
 */
export interface V1CreateActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateActivityRequest
     */
    'name': string;
    /**
     * 
     * @type {Array<V1TicketingMedia>}
     * @memberof V1CreateActivityRequest
     */
    'medias'?: Array<V1TicketingMedia>;
    /**
     * 
     * @type {string}
     * @memberof V1CreateActivityRequest
     */
    'desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateActivityRequest
     */
    'shortDesc'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1CreateActivityRequest
     */
    'content'?: object;
}

