/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Ticket } from './v1-ticket';

/**
 * 
 * @export
 * @interface V1ListTicketReply
 */
export interface V1ListTicketReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListTicketReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListTicketReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1Ticket>}
     * @memberof V1ListTicketReply
     */
    'items'?: Array<V1Ticket>;
}

