/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1UpdateShow } from './v1-update-show';

/**
 * 
 * @export
 * @interface V1UpdateShowRequest
 */
export interface V1UpdateShowRequest {
    /**
     * 
     * @type {V1UpdateShow}
     * @memberof V1UpdateShowRequest
     */
    'show'?: V1UpdateShow;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateShowRequest
     */
    'updateMask'?: string;
}

