/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Seat } from './v1-seat';
import { V1UpdateSeatGroup } from './v1-update-seat-group';

/**
 * 
 * @export
 * @interface V1UpdateLocationHall
 */
export interface V1UpdateLocationHall {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateLocationHall
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateLocationHall
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateLocationHall
     */
    'tags'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1UpdateLocationHall
     */
    'capacity'?: number;
    /**
     * 
     * @type {Array<V1UpdateSeatGroup>}
     * @memberof V1UpdateLocationHall
     */
    'seatGroups'?: Array<V1UpdateSeatGroup>;
    /**
     * 
     * @type {Array<V1Seat>}
     * @memberof V1UpdateLocationHall
     */
    'seats'?: Array<V1Seat>;
}

