// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ticketing/api/banner/v1/banner.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListAppBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAppBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAppBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAppBannerRequestMultiError, or nil if none found.
func (m *ListAppBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAppBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListAppBannerRequestMultiError(errors)
	}

	return nil
}

// ListAppBannerRequestMultiError is an error wrapping multiple validation
// errors returned by ListAppBannerRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAppBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAppBannerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAppBannerRequestMultiError) AllErrors() []error { return m }

// ListAppBannerRequestValidationError is the validation error returned by
// ListAppBannerRequest.Validate if the designated constraints aren't met.
type ListAppBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAppBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAppBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAppBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAppBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAppBannerRequestValidationError) ErrorName() string {
	return "ListAppBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAppBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAppBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAppBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAppBannerRequestValidationError{}

// Validate checks the field values on ListAppBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAppBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAppBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAppBannerReplyMultiError, or nil if none found.
func (m *ListAppBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAppBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAppBannerReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAppBannerReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAppBannerReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAppBannerReplyMultiError(errors)
	}

	return nil
}

// ListAppBannerReplyMultiError is an error wrapping multiple validation errors
// returned by ListAppBannerReply.ValidateAll() if the designated constraints
// aren't met.
type ListAppBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAppBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAppBannerReplyMultiError) AllErrors() []error { return m }

// ListAppBannerReplyValidationError is the validation error returned by
// ListAppBannerReply.Validate if the designated constraints aren't met.
type ListAppBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAppBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAppBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAppBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAppBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAppBannerReplyValidationError) ErrorName() string {
	return "ListAppBannerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListAppBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAppBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAppBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAppBannerReplyValidationError{}

// Validate checks the field values on CreateBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBannerRequestMultiError, or nil if none found.
func (m *CreateBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRefType()) < 1 {
		err := CreateBannerRequestValidationError{
			field:  "RefType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRefId()) < 1 {
		err := CreateBannerRequestValidationError{
			field:  "RefId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMainPic() == nil {
		err := CreateBannerRequestValidationError{
			field:  "MainPic",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMainPic()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBannerRequestValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBannerRequestValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMainPic()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBannerRequestValidationError{
				field:  "MainPic",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateBannerRequestMultiError(errors)
	}

	return nil
}

// CreateBannerRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBannerRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBannerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBannerRequestMultiError) AllErrors() []error { return m }

// CreateBannerRequestValidationError is the validation error returned by
// CreateBannerRequest.Validate if the designated constraints aren't met.
type CreateBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBannerRequestValidationError) ErrorName() string {
	return "CreateBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBannerRequestValidationError{}

// Validate checks the field values on UpdateBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBannerRequestMultiError, or nil if none found.
func (m *UpdateBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetBanner() == nil {
		err := UpdateBannerRequestValidationError{
			field:  "Banner",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetBanner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateBannerRequestValidationError{
					field:  "Banner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateBannerRequestValidationError{
					field:  "Banner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBanner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBannerRequestValidationError{
				field:  "Banner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateMask()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateBannerRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateBannerRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBannerRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateBannerRequestMultiError(errors)
	}

	return nil
}

// UpdateBannerRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateBannerRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerRequestMultiError) AllErrors() []error { return m }

// UpdateBannerRequestValidationError is the validation error returned by
// UpdateBannerRequest.Validate if the designated constraints aren't met.
type UpdateBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerRequestValidationError) ErrorName() string {
	return "UpdateBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerRequestValidationError{}

// Validate checks the field values on UpdateBanner with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UpdateBanner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBanner with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UpdateBannerMultiError, or
// nil if none found.
func (m *UpdateBanner) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBanner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateBannerValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRefType()) < 1 {
		err := UpdateBannerValidationError{
			field:  "RefType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRefId()) < 1 {
		err := UpdateBannerValidationError{
			field:  "RefId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMainPic() == nil {
		err := UpdateBannerValidationError{
			field:  "MainPic",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMainPic()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateBannerValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateBannerValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMainPic()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBannerValidationError{
				field:  "MainPic",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := _UpdateBanner_Status_InLookup[m.GetStatus()]; !ok {
		err := UpdateBannerValidationError{
			field:  "Status",
			reason: "value must be in list [UNPUBLISHED PUBLISHED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStatus()) < 1 {
		err := UpdateBannerValidationError{
			field:  "Status",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateBannerMultiError(errors)
	}

	return nil
}

// UpdateBannerMultiError is an error wrapping multiple validation errors
// returned by UpdateBanner.ValidateAll() if the designated constraints aren't met.
type UpdateBannerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerMultiError) AllErrors() []error { return m }

// UpdateBannerValidationError is the validation error returned by
// UpdateBanner.Validate if the designated constraints aren't met.
type UpdateBannerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerValidationError) ErrorName() string { return "UpdateBannerValidationError" }

// Error satisfies the builtin error interface
func (e UpdateBannerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBanner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerValidationError{}

var _UpdateBanner_Status_InLookup = map[string]struct{}{
	"UNPUBLISHED": {},
	"PUBLISHED":   {},
}

// Validate checks the field values on DeleteBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBannerRequestMultiError, or nil if none found.
func (m *DeleteBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteBannerRequestMultiError(errors)
	}

	return nil
}

// DeleteBannerRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteBannerRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBannerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBannerRequestMultiError) AllErrors() []error { return m }

// DeleteBannerRequestValidationError is the validation error returned by
// DeleteBannerRequest.Validate if the designated constraints aren't met.
type DeleteBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBannerRequestValidationError) ErrorName() string {
	return "DeleteBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBannerRequestValidationError{}

// Validate checks the field values on DeleteBannerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBannerReplyMultiError, or nil if none found.
func (m *DeleteBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteBannerReplyMultiError(errors)
	}

	return nil
}

// DeleteBannerReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteBannerReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBannerReplyMultiError) AllErrors() []error { return m }

// DeleteBannerReplyValidationError is the validation error returned by
// DeleteBannerReply.Validate if the designated constraints aren't met.
type DeleteBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBannerReplyValidationError) ErrorName() string {
	return "DeleteBannerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBannerReplyValidationError{}

// Validate checks the field values on BannerFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BannerFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BannerFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BannerFilterMultiError, or
// nil if none found.
func (m *BannerFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *BannerFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BannerFilterValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BannerFilterValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BannerFilterValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BannerFilterMultiError(errors)
	}

	return nil
}

// BannerFilterMultiError is an error wrapping multiple validation errors
// returned by BannerFilter.ValidateAll() if the designated constraints aren't met.
type BannerFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BannerFilterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BannerFilterMultiError) AllErrors() []error { return m }

// BannerFilterValidationError is the validation error returned by
// BannerFilter.Validate if the designated constraints aren't met.
type BannerFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BannerFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BannerFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BannerFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BannerFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BannerFilterValidationError) ErrorName() string { return "BannerFilterValidationError" }

// Error satisfies the builtin error interface
func (e BannerFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBannerFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BannerFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BannerFilterValidationError{}

// Validate checks the field values on ListBannerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBannerRequestMultiError, or nil if none found.
func (m *ListBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageOffset

	// no validation rules for PageSize

	// no validation rules for Search

	if all {
		switch v := interface{}(m.GetFields()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListBannerRequestValidationError{
					field:  "Fields",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListBannerRequestValidationError{
					field:  "Fields",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFields()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListBannerRequestValidationError{
				field:  "Fields",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListBannerRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListBannerRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListBannerRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListBannerRequestMultiError(errors)
	}

	return nil
}

// ListBannerRequestMultiError is an error wrapping multiple validation errors
// returned by ListBannerRequest.ValidateAll() if the designated constraints
// aren't met.
type ListBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBannerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBannerRequestMultiError) AllErrors() []error { return m }

// ListBannerRequestValidationError is the validation error returned by
// ListBannerRequest.Validate if the designated constraints aren't met.
type ListBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBannerRequestValidationError) ErrorName() string {
	return "ListBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBannerRequestValidationError{}

// Validate checks the field values on ListBannerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBannerReplyMultiError, or nil if none found.
func (m *ListBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalSize

	// no validation rules for FilterSize

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBannerReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBannerReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBannerReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListBannerReplyMultiError(errors)
	}

	return nil
}

// ListBannerReplyMultiError is an error wrapping multiple validation errors
// returned by ListBannerReply.ValidateAll() if the designated constraints
// aren't met.
type ListBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBannerReplyMultiError) AllErrors() []error { return m }

// ListBannerReplyValidationError is the validation error returned by
// ListBannerReply.Validate if the designated constraints aren't met.
type ListBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBannerReplyValidationError) ErrorName() string { return "ListBannerReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBannerReplyValidationError{}

// Validate checks the field values on Banner with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Banner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Banner with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BannerMultiError, or nil if none found.
func (m *Banner) ValidateAll() error {
	return m.validate(true)
}

func (m *Banner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for RefType

	// no validation rules for RefId

	if all {
		switch v := interface{}(m.GetMainPic()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BannerValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BannerValidationError{
					field:  "MainPic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMainPic()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BannerValidationError{
				field:  "MainPic",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return BannerMultiError(errors)
	}

	return nil
}

// BannerMultiError is an error wrapping multiple validation errors returned by
// Banner.ValidateAll() if the designated constraints aren't met.
type BannerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BannerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BannerMultiError) AllErrors() []error { return m }

// BannerValidationError is the validation error returned by Banner.Validate if
// the designated constraints aren't met.
type BannerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BannerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BannerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BannerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BannerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BannerValidationError) ErrorName() string { return "BannerValidationError" }

// Error satisfies the builtin error interface
func (e BannerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBanner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BannerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BannerValidationError{}
