/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1Activity } from '../models';
// @ts-ignore
import { V1CreateActivityRequest } from '../models';
// @ts-ignore
import { V1DeleteActivityReply } from '../models';
// @ts-ignore
import { V1ListActivityReply } from '../models';
// @ts-ignore
import { V1ListActivityRequest } from '../models';
// @ts-ignore
import { V1UpdateActivityRequest } from '../models';
/**
 * ActivityServiceApi - axios parameter creator
 * @export
 */
export const ActivityServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1CreateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceCreateActivity: async (body: V1CreateActivityRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('activityServiceCreateActivity', 'body', body)
            const localVarPath = `/v1/ticketing/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceDeleteActivity: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activityServiceDeleteActivity', 'id', id)
            const localVarPath = `/v1/ticketing/activity/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceGetActivity: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activityServiceGetActivity', 'id', id)
            const localVarPath = `/v1/ticketing/activity/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceListActivity: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ticketing/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1ListActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceListActivity2: async (body: V1ListActivityRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('activityServiceListActivity2', 'body', body)
            const localVarPath = `/v1/ticketing/activity/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceUpdateActivity: async (activityId: string, body: V1UpdateActivityRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityServiceUpdateActivity', 'activityId', activityId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('activityServiceUpdateActivity', 'body', body)
            const localVarPath = `/v1/ticketing/activity/{activity.id}`
                .replace(`{${"activity.id"}}`, encodeURIComponent(String(activityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceUpdateActivity2: async (activityId: string, body: V1UpdateActivityRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityServiceUpdateActivity2', 'activityId', activityId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('activityServiceUpdateActivity2', 'body', body)
            const localVarPath = `/v1/ticketing/activity/{activity.id}`
                .replace(`{${"activity.id"}}`, encodeURIComponent(String(activityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ActivityServiceApi - functional programming interface
 * @export
 */
export const ActivityServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ActivityServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1CreateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceCreateActivity(body: V1CreateActivityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceCreateActivity(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceDeleteActivity(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1DeleteActivityReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceDeleteActivity(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceGetActivity(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceGetActivity(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceListActivity(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListActivityReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceListActivity(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {V1ListActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceListActivity2(body: V1ListActivityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListActivityReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceListActivity2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceUpdateActivity(activityId: string, body: V1UpdateActivityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceUpdateActivity(activityId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityServiceUpdateActivity2(activityId: string, body: V1UpdateActivityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityServiceUpdateActivity2(activityId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ActivityServiceApi - factory interface
 * @export
 */
export const ActivityServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ActivityServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {V1CreateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceCreateActivity(body: V1CreateActivityRequest, options?: any): AxiosPromise<V1Activity> {
            return localVarFp.activityServiceCreateActivity(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceDeleteActivity(id: string, options?: any): AxiosPromise<V1DeleteActivityReply> {
            return localVarFp.activityServiceDeleteActivity(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceGetActivity(id: string, options?: any): AxiosPromise<V1Activity> {
            return localVarFp.activityServiceGetActivity(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceListActivity(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options?: any): AxiosPromise<V1ListActivityReply> {
            return localVarFp.activityServiceListActivity(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {V1ListActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceListActivity2(body: V1ListActivityRequest, options?: any): AxiosPromise<V1ListActivityReply> {
            return localVarFp.activityServiceListActivity2(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceUpdateActivity(activityId: string, body: V1UpdateActivityRequest, options?: any): AxiosPromise<V1Activity> {
            return localVarFp.activityServiceUpdateActivity(activityId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} activityId 
         * @param {V1UpdateActivityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityServiceUpdateActivity2(activityId: string, body: V1UpdateActivityRequest, options?: any): AxiosPromise<V1Activity> {
            return localVarFp.activityServiceUpdateActivity2(activityId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for activityServiceCreateActivity operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceCreateActivityRequest
 */
export interface ActivityServiceApiActivityServiceCreateActivityRequest {
    /**
     * 
     * @type {V1CreateActivityRequest}
     * @memberof ActivityServiceApiActivityServiceCreateActivity
     */
    readonly body: V1CreateActivityRequest
}

/**
 * Request parameters for activityServiceDeleteActivity operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceDeleteActivityRequest
 */
export interface ActivityServiceApiActivityServiceDeleteActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceDeleteActivity
     */
    readonly id: string
}

/**
 * Request parameters for activityServiceGetActivity operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceGetActivityRequest
 */
export interface ActivityServiceApiActivityServiceGetActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceGetActivity
     */
    readonly id: string
}

/**
 * Request parameters for activityServiceListActivity operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceListActivityRequest
 */
export interface ActivityServiceApiActivityServiceListActivityRequest {
    /**
     * 
     * @type {number}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceListActivity
     */
    readonly filterName$like?: string
}

/**
 * Request parameters for activityServiceListActivity2 operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceListActivity2Request
 */
export interface ActivityServiceApiActivityServiceListActivity2Request {
    /**
     * 
     * @type {V1ListActivityRequest}
     * @memberof ActivityServiceApiActivityServiceListActivity2
     */
    readonly body: V1ListActivityRequest
}

/**
 * Request parameters for activityServiceUpdateActivity operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceUpdateActivityRequest
 */
export interface ActivityServiceApiActivityServiceUpdateActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceUpdateActivity
     */
    readonly activityId: string

    /**
     * 
     * @type {V1UpdateActivityRequest}
     * @memberof ActivityServiceApiActivityServiceUpdateActivity
     */
    readonly body: V1UpdateActivityRequest
}

/**
 * Request parameters for activityServiceUpdateActivity2 operation in ActivityServiceApi.
 * @export
 * @interface ActivityServiceApiActivityServiceUpdateActivity2Request
 */
export interface ActivityServiceApiActivityServiceUpdateActivity2Request {
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceApiActivityServiceUpdateActivity2
     */
    readonly activityId: string

    /**
     * 
     * @type {V1UpdateActivityRequest}
     * @memberof ActivityServiceApiActivityServiceUpdateActivity2
     */
    readonly body: V1UpdateActivityRequest
}

/**
 * ActivityServiceApi - object-oriented interface
 * @export
 * @class ActivityServiceApi
 * @extends {BaseAPI}
 */
export class ActivityServiceApi extends BaseAPI {
    /**
     * 
     * @param {ActivityServiceApiActivityServiceCreateActivityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceCreateActivity(requestParameters: ActivityServiceApiActivityServiceCreateActivityRequest, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceCreateActivity(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceDeleteActivityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceDeleteActivity(requestParameters: ActivityServiceApiActivityServiceDeleteActivityRequest, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceDeleteActivity(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceGetActivityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceGetActivity(requestParameters: ActivityServiceApiActivityServiceGetActivityRequest, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceGetActivity(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceListActivityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceListActivity(requestParameters: ActivityServiceApiActivityServiceListActivityRequest = {}, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceListActivity(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceListActivity2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceListActivity2(requestParameters: ActivityServiceApiActivityServiceListActivity2Request, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceListActivity2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceUpdateActivityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceUpdateActivity(requestParameters: ActivityServiceApiActivityServiceUpdateActivityRequest, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceUpdateActivity(requestParameters.activityId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ActivityServiceApiActivityServiceUpdateActivity2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityServiceApi
     */
    public activityServiceUpdateActivity2(requestParameters: ActivityServiceApiActivityServiceUpdateActivity2Request, options?: AxiosRequestConfig) {
        return ActivityServiceApiFp(this.configuration).activityServiceUpdateActivity2(requestParameters.activityId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
