/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1CreateOrderRequest } from '../models';
// @ts-ignore
import { V1DeleteOrderReply } from '../models';
// @ts-ignore
import { V1ListOrderReply } from '../models';
// @ts-ignore
import { V1ListOrderRequest } from '../models';
// @ts-ignore
import { V1Order } from '../models';
// @ts-ignore
import { V1UpdateOrderRequest } from '../models';
/**
 * OrderServiceApi - axios parameter creator
 * @export
 */
export const OrderServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1CreateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceCreateOrder: async (body: V1CreateOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('orderServiceCreateOrder', 'body', body)
            const localVarPath = `/v1/order/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceDeleteOrder: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('orderServiceDeleteOrder', 'id', id)
            const localVarPath = `/v1/order/order/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceGetOrder: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('orderServiceGetOrder', 'id', id)
            const localVarPath = `/v1/order/order/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceListOrder: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/order/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1ListOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceListOrder2: async (body: V1ListOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('orderServiceListOrder2', 'body', body)
            const localVarPath = `/v1/order/order/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceUpdateOrder: async (orderId: string, body: V1UpdateOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('orderServiceUpdateOrder', 'orderId', orderId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('orderServiceUpdateOrder', 'body', body)
            const localVarPath = `/v1/order/order/{order.id}`
                .replace(`{${"order.id"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceUpdateOrder2: async (orderId: string, body: V1UpdateOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('orderServiceUpdateOrder2', 'orderId', orderId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('orderServiceUpdateOrder2', 'body', body)
            const localVarPath = `/v1/order/order/{order.id}`
                .replace(`{${"order.id"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrderServiceApi - functional programming interface
 * @export
 */
export const OrderServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrderServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1CreateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceCreateOrder(body: V1CreateOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Order>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceCreateOrder(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceDeleteOrder(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1DeleteOrderReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceDeleteOrder(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceGetOrder(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Order>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceGetOrder(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceListOrder(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListOrderReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceListOrder(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {V1ListOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceListOrder2(body: V1ListOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListOrderReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceListOrder2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceUpdateOrder(orderId: string, body: V1UpdateOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Order>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceUpdateOrder(orderId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderServiceUpdateOrder2(orderId: string, body: V1UpdateOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Order>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderServiceUpdateOrder2(orderId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OrderServiceApi - factory interface
 * @export
 */
export const OrderServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrderServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {V1CreateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceCreateOrder(body: V1CreateOrderRequest, options?: any): AxiosPromise<V1Order> {
            return localVarFp.orderServiceCreateOrder(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceDeleteOrder(id: string, options?: any): AxiosPromise<V1DeleteOrderReply> {
            return localVarFp.orderServiceDeleteOrder(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceGetOrder(id: string, options?: any): AxiosPromise<V1Order> {
            return localVarFp.orderServiceGetOrder(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceListOrder(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options?: any): AxiosPromise<V1ListOrderReply> {
            return localVarFp.orderServiceListOrder(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {V1ListOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceListOrder2(body: V1ListOrderRequest, options?: any): AxiosPromise<V1ListOrderReply> {
            return localVarFp.orderServiceListOrder2(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceUpdateOrder(orderId: string, body: V1UpdateOrderRequest, options?: any): AxiosPromise<V1Order> {
            return localVarFp.orderServiceUpdateOrder(orderId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} orderId 
         * @param {V1UpdateOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderServiceUpdateOrder2(orderId: string, body: V1UpdateOrderRequest, options?: any): AxiosPromise<V1Order> {
            return localVarFp.orderServiceUpdateOrder2(orderId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for orderServiceCreateOrder operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceCreateOrderRequest
 */
export interface OrderServiceApiOrderServiceCreateOrderRequest {
    /**
     * 
     * @type {V1CreateOrderRequest}
     * @memberof OrderServiceApiOrderServiceCreateOrder
     */
    readonly body: V1CreateOrderRequest
}

/**
 * Request parameters for orderServiceDeleteOrder operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceDeleteOrderRequest
 */
export interface OrderServiceApiOrderServiceDeleteOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceDeleteOrder
     */
    readonly id: string
}

/**
 * Request parameters for orderServiceGetOrder operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceGetOrderRequest
 */
export interface OrderServiceApiOrderServiceGetOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceGetOrder
     */
    readonly id: string
}

/**
 * Request parameters for orderServiceListOrder operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceListOrderRequest
 */
export interface OrderServiceApiOrderServiceListOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceListOrder
     */
    readonly filterName$like?: string
}

/**
 * Request parameters for orderServiceListOrder2 operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceListOrder2Request
 */
export interface OrderServiceApiOrderServiceListOrder2Request {
    /**
     * 
     * @type {V1ListOrderRequest}
     * @memberof OrderServiceApiOrderServiceListOrder2
     */
    readonly body: V1ListOrderRequest
}

/**
 * Request parameters for orderServiceUpdateOrder operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceUpdateOrderRequest
 */
export interface OrderServiceApiOrderServiceUpdateOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceUpdateOrder
     */
    readonly orderId: string

    /**
     * 
     * @type {V1UpdateOrderRequest}
     * @memberof OrderServiceApiOrderServiceUpdateOrder
     */
    readonly body: V1UpdateOrderRequest
}

/**
 * Request parameters for orderServiceUpdateOrder2 operation in OrderServiceApi.
 * @export
 * @interface OrderServiceApiOrderServiceUpdateOrder2Request
 */
export interface OrderServiceApiOrderServiceUpdateOrder2Request {
    /**
     * 
     * @type {string}
     * @memberof OrderServiceApiOrderServiceUpdateOrder2
     */
    readonly orderId: string

    /**
     * 
     * @type {V1UpdateOrderRequest}
     * @memberof OrderServiceApiOrderServiceUpdateOrder2
     */
    readonly body: V1UpdateOrderRequest
}

/**
 * OrderServiceApi - object-oriented interface
 * @export
 * @class OrderServiceApi
 * @extends {BaseAPI}
 */
export class OrderServiceApi extends BaseAPI {
    /**
     * 
     * @param {OrderServiceApiOrderServiceCreateOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceCreateOrder(requestParameters: OrderServiceApiOrderServiceCreateOrderRequest, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceCreateOrder(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceDeleteOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceDeleteOrder(requestParameters: OrderServiceApiOrderServiceDeleteOrderRequest, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceDeleteOrder(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceGetOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceGetOrder(requestParameters: OrderServiceApiOrderServiceGetOrderRequest, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceGetOrder(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceListOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceListOrder(requestParameters: OrderServiceApiOrderServiceListOrderRequest = {}, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceListOrder(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceListOrder2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceListOrder2(requestParameters: OrderServiceApiOrderServiceListOrder2Request, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceListOrder2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceUpdateOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceUpdateOrder(requestParameters: OrderServiceApiOrderServiceUpdateOrderRequest, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceUpdateOrder(requestParameters.orderId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderServiceApiOrderServiceUpdateOrder2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderServiceApi
     */
    public orderServiceUpdateOrder2(requestParameters: OrderServiceApiOrderServiceUpdateOrder2Request, options?: AxiosRequestConfig) {
        return OrderServiceApiFp(this.configuration).orderServiceUpdateOrder2(requestParameters.orderId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
