serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    #publich hydra server
    issuer: http://localhost

#  consent: http://127.0.0.1:7090/user/consent
#  login: http://127.0.0.1:7090/user/login
#  logout: http://127.0.0.1:7090/user/logout
  consent: http://127.0.0.1/user/consent
  login: http://127.0.0.1/user/login
  logout: http://127.0.0.1/user/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
