// Code generated by protoc-gen-go-grpc-proxy. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-proxy v1.2.0
// - protoc             (unknown)
// source: ticketing/api/show/v1/show_app.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var _ ShowAppServiceServer = (*showAppServiceClientProxy)(nil)

const GrpcOperationShowAppServiceListAppShow = "/ticketing.api.show.v1.ShowAppService/ListAppShow"
const GrpcOperationShowAppServiceGetAppShow = "/ticketing.api.show.v1.ShowAppService/GetAppShow"
const GrpcOperationShowAppServicePlaceShowOrder = "/ticketing.api.show.v1.ShowAppService/PlaceShowOrder"

// showAppServiceClientProxy is the proxy to turn ShowAppService client to server interface.
type showAppServiceClientProxy struct {
	cc ShowAppServiceClient
}

func NewShowAppServiceClientProxy(cc ShowAppServiceClient) ShowAppServiceServer {
	return &showAppServiceClientProxy{cc}
}

func (c *showAppServiceClientProxy) ListAppShow(ctx context.Context, in *ListShowRequest) (*ListShowReply, error) {
	return c.cc.ListAppShow(ctx, in)
}
func (c *showAppServiceClientProxy) GetAppShow(ctx context.Context, in *GetShowRequest) (*Show, error) {
	return c.cc.GetAppShow(ctx, in)
}
func (c *showAppServiceClientProxy) PlaceShowOrder(ctx context.Context, in *PlaceShowOrderRequest) (*PlaceShowOrderReply, error) {
	return c.cc.PlaceShowOrder(ctx, in)
}
