// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: order/api/order/v1/order_internal.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateInternalOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInternalOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInternalOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInternalOrderRequestMultiError, or nil if none found.
func (m *CreateInternalOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInternalOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTotalPrice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "TotalPrice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "TotalPrice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTotalPrice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInternalOrderRequestValidationError{
				field:  "TotalPrice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetShippingAddr()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "ShippingAddr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "ShippingAddr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetShippingAddr()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInternalOrderRequestValidationError{
				field:  "ShippingAddr",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBillingAddr()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "BillingAddr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInternalOrderRequestValidationError{
					field:  "BillingAddr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBillingAddr()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInternalOrderRequestValidationError{
				field:  "BillingAddr",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInternalOrderRequestMultiError(errors)
	}

	return nil
}

// CreateInternalOrderRequestMultiError is an error wrapping multiple
// validation errors returned by CreateInternalOrderRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateInternalOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInternalOrderRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInternalOrderRequestMultiError) AllErrors() []error { return m }

// CreateInternalOrderRequestValidationError is the validation error returned
// by CreateInternalOrderRequest.Validate if the designated constraints aren't met.
type CreateInternalOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInternalOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInternalOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInternalOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInternalOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInternalOrderRequestValidationError) ErrorName() string {
	return "CreateInternalOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInternalOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInternalOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInternalOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInternalOrderRequestValidationError{}
