payment:
  methods:
    default:
      stripe:
        is_test: true
        private_key: sk_test_51GqvR7JYyL5pFgToLCVoHxhFtAwZv0Fd6SHuHZdT3LHPSfcj3FqcxMAG7atHAwcF0FaUJ6SrlObZh6RMteHLxBqz00qrjLMhdI
        webhook_key: whsec_trKMODLAHgrNcJuL4SleEEFRxG0JYzVY
