services:
  servers:
    default:
      http:
        timeout: 200s
        cors:
          allowed_origins: [ "*" ]
    payment:
      http:
        addr: 0.0.0.0:9500
      grpc:
        addr: 0.0.0.0:9501
  services:
    user: {}
    saas: {}
  clients:
    payment:
      client_id: payment-golang
  registry:
    type: etcd
    endpoint: http://localhost:3379

data:
  endpoints:
    databases:
        default:
          driver: sqlite
          source: "file::memory:?loc=Local"
          table_prefix: ""
  blobs:
    payment:
      provider: os
      public_url: http://localhost:9500
      base_path: "assets/payment"
      os:
        dir: "./.temp"

security:
  jwt:
    expire_in: 2592000s #    30 days
    secret: 6efa4458-b245-40a3-9685-6b30d5dcda49
  security_cookie:
    hash: gt35ofggk07kdt7ief99bl51avd7pbhe
