name: Docker Image Microservice CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  DOCKER_TAG: dev

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.ms.yml build

      - name: Docker login

        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.ms.yml push

          
